#!/usr/bin/env bash
# Decrypt menu module. Only supports files generated by BogelShell Protect v2.

decrypt_menu() {
  local input output vars var line value payload decode_cmd

  printf "\n%bInput encrypted file :%b " "$YELLOW" "$RESET"
  IFS= read -r input
  validate_readable_file "$input" || return 1
  require_command gzip base64 rev grep sed awk || return 1

  if ! grep -q '^# BOGELSHELL_PROTECT_V2_BEGIN' "$input" || ! grep -q '^# BSP_FORMAT=BOGELSHELL_PROTECT_V2' "$input"; then
    error "Invalid encrypted file. Format/header salah."
    return 1
  fi

  vars=$(sed -n 's/^# BSP_VARS=//p' "$input" | head -n 1)
  if [ -z "$vars" ]; then
    error "Invalid encrypted file. Metadata payload tidak ditemukan."
    return 1
  fi

  printf "%bOutput file          :%b " "$YELLOW" "$RESET"
  IFS= read -r output
  validate_output_path "$output" || return 1

  progress_step "Reading Encrypted File..."
  payload=""
  for var in $vars; do
    case "$var" in
      *[!A-Za-z]*|'') error "Invalid encrypted file. Nama payload rusak."; return 1 ;;
    esac
    line=$(grep -m 1 "^${var}=" "$input" || true)
    if [ -z "$line" ]; then
      error "Invalid encrypted file. Payload part hilang: $var"
      return 1
    fi
    value=${line#*=}
    # Values were generated by Bash printf %q. Metadata header ensures this parser
    # only targets BogelShell Protect files.
    eval "value=$value" 2>/dev/null || {
      error "Invalid encrypted file. Payload part rusak."
      return 1
    }
    payload="${payload}${value}"
  done

  if [ -z "$payload" ]; then
    error "Invalid encrypted file. Payload kosong."
    return 1
  fi

  progress_step "Reversing Payload..."
  decode_cmd=$(base64_decode_cmd)
  if ! printf "%s" "$payload" | rev | $decode_cmd | gzip -dc > "$output" 2>/dev/null; then
    rm -f "$output"
    error "Invalid encrypted file. Payload rusak atau tidak bisa didecode."
    return 1
  fi

  if [ ! -s "$output" ]; then
    rm -f "$output"
    error "Invalid encrypted file. Hasil decrypt kosong."
    return 1
  fi

  chmod +x "$output" 2>/dev/null || warn "Output berhasil dibuat, tetapi chmod +x gagal."
  progress_step "Writing Output..."
  success "Done: $output"
}
