#!/usr/bin/env bash
# Builder for encrypted loader files.

build_encrypted_script() {
  # Args: input output
  local input=$1 output=$2 temp payload chunk_size total len i part var vars eval_var printf_var echo_var decode_cmd fn_name dummy_count dummy_name dummy_value

  temp=$(mktemp 2>/dev/null || printf "/tmp/bsp_%s" "$RANDOM$RANDOM")
  : > "$temp" || { error "Gagal membuat temporary file."; return 1; }

  progress_step "Reading Script..."
  if ! gzip -c -- "$input" 2>/dev/null | base64 | rev > "$temp"; then
    rm -f "$temp"
    error "Gagal melakukan gzip/base64/rev."
    return 1
  fi

  progress_step "Encoding Base64..."
  payload=$(cat "$temp")
  rm -f "$temp"
  if [ -z "$payload" ]; then
    error "Payload kosong setelah proses encode."
    return 1
  fi

  progress_step "Randomizing Variable..."
  eval_var=$(random_name)
  printf_var=$(random_name)
  echo_var=$(random_name)
  fn_name=$(random_name)
  decode_cmd=$(base64_decode_cmd)

  len=${#payload}
  total=$((4 + RANDOM % 5))
  chunk_size=$(((len + total - 1) / total))

  vars=""
  i=1
  while [ "$i" -le "$total" ]; do
    var=$(random_name)
    vars="$vars $var"
    i=$((i + 1))
  done

  progress_step "Building Loader..."
  {
    printf '#!/usr/bin/env bash\n'
    printf '# =========================================================\n'
    printf '# BOGELSHELL PROTECT - Protected Bash Script\n'
    printf '# Generated by BogelShell Protect v2.0\n'
    printf '# This is obfuscation, not real cryptographic encryption.\n'
    printf '# =========================================================\n'
    printf '# BOGELSHELL_PROTECT_V2_BEGIN\n'
    printf '# BSP_FORMAT=BOGELSHELL_PROTECT_V2\n'
    printf '# BSP_CHUNK_COUNT=%s\n' "$total"
    printf '# BSP_VARS=%s\n' "${vars# }"
    printf '# BSP_DATA_BEGIN\n'

    # More than 500 random dummy variables.
    dummy_count=0
    while [ "$dummy_count" -lt 520 ]; do
      dummy_name=$(random_name)
      dummy_value=$(random_text $((8 + RANDOM % 28)))
      printf '%s=%q\n' "$dummy_name" "$dummy_value"
      dummy_count=$((dummy_count + 1))
      # Random whitespace / harmless dummy code.
      if [ $((dummy_count % 17)) -eq 0 ]; then
        printf ' : ${%s:=\"%s\"} >/dev/null 2>&1 || true\n' "$(random_name)" "$(random_text 10)"
      fi
    done

    eval_var_value='eval'
    printf '%s=%q\n' "$eval_var" "$eval_var_value"
    printf '%s=%q\n' "$printf_var" 'printf'
    printf '%s=%q\n' "$echo_var" 'echo'

    i=0
    for var in $vars; do
      part=${payload:i:chunk_size}
      printf '%s=%q\n' "$var" "$part"
      i=$((i + chunk_size))
    done

    printf '# BSP_DATA_END\n'
    printf '%s() {\n' "$fn_name"
    printf '  local _bsp_payload="" _bsp_decoded=""\n'
    printf '  _bsp_payload='
    for var in $vars; do
      printf '"$%s"' "$var"
    done
    printf '\n'
    printf '  if [ -z "$_bsp_payload" ]; then echo "Invalid encrypted file." >&2; exit 1; fi\n'
    printf '  _bsp_decoded=$($%s "%%s" "$_bsp_payload" | rev | %s | gzip -dc 2>/dev/null) || { echo "Invalid encrypted file." >&2; exit 1; }\n' "$printf_var" "$decode_cmd"
    printf '  $%s "$_bsp_decoded"\n' "$eval_var"
    printf '}\n'
    printf '%s "$@"\n' "$fn_name"
    printf '# BOGELSHELL_PROTECT_V2_END\n'
  } > "$output" || {
    error "Gagal menulis output."
    return 1
  }

  chmod +x "$output" 2>/dev/null || warn "Output berhasil dibuat, tetapi chmod +x gagal."
  progress_step "Writing Output..."
  success "Done: $output"
}
